export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const USER_INPUT_DATA = 'USER_INPUT_DATA';
export const USER_INPUT_DATA_ERROR = 'USER_INPUT_DATA_ERROR';

export const FETCH_COMPANIES_REQUEST = 'FETCH_COMPANIES_REQUEST';
export const FETCH_COMPANY_REQUEST = 'FETCH_COMPANY_REQUEST';
export const FETCH_COMPANY_FAILED = 'FETCH_COMPANY_FAILED';
export const RESET_COMPANY = 'RESET_COMPANY';
export const COMPANY_DATA_CHANGE = 'COMPANY_DATA_CHANGE';
export const FAILED_COMPANY_REQUEST = 'FAILED_COMPANY_REQUEST';
export const COMPANY_LOGO_FILE = 'COMPANY_LOGO_FILE';
export const COMPANY_LOGO = 'COMPANY_LOGO';

export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST';
export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST';
export const FETCH_EMPLOYEE_FAILED = 'FETCH_EMPLOYEE_FAILED';
export const RESET_EMPLOYEE = 'RESET_EMPLOYEE';
export const EMPLOYEE_DATA_CHANGE = 'EMPLOYEE_DATA_CHANGE';
export const FAILED_EMPLOYEE_REQUEST = 'FAILED_EMPLOYEE_REQUEST';